# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
  - test
  - release

before_script:
  - npm install

release-test:
  image: node:18
  stage: test
  script:
    - env
    - npm i
    - npm run release:check
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'next' || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'beta' || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'alpha'

publish:
  image: node:18
  stage: release
  script:
    - env
    - npm i
    - npm run release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == 'next' || $CI_COMMIT_BRANCH == 'beta' || $CI_COMMIT_BRANCH == 'alpha'