# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
  - test
  - release

before_script:
  - npm install

release-test:
  image: node:18
  stage: test
  script:
    - npm i
    - npm run release:check
    - echo "$CI_COMMIT_BRANCH"
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH != 'next' || $CI_COMMIT_BRANCH != 'beta' || $CI_COMMIT_BRANCH != 'alpha'

publish:
  image: node:18
  stage: release
  script:
    - npm i
    - npm run release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == 'next' || $CI_COMMIT_BRANCH == 'beta' || $CI_COMMIT_BRANCH == 'alpha'