# The release pipeline will run only if all jobs in the test pipeline are successful

.semantic-branches: &semantic-branches
  if: >-
    $CI_COMMIT_REF_NAME == "main" ||
    $CI_COMMIT_REF_NAME == "next" ||
    $CI_COMMIT_REF_NAME == "next-major" ||
    $CI_COMMIT_REF_NAME == "alpha" ||
    $CI_COMMIT_REF_NAME == "beta"
  when: on_success

.non-semantic-branches: &non-semantic-branches
  if: >-
    $CI_COMMIT_REF_NAME != "main" ||
    $CI_COMMIT_REF_NAME != "next" ||
    $CI_COMMIT_REF_NAME != "next-major" ||
    $CI_COMMIT_REF_NAME != "alpha" ||
    $CI_COMMIT_REF_NAME != "beta"
  when: on_success


stages:
  - test
  - release

before_script:
  - npm install

release-test:
  image: node:18
  stage: test
  script:
    - npm run release:check
  rules:
    - *non-semantic-branches


publish:
  image: node:18
  stage: release
  script:
    - npm run release
  rules:
    - *semantic-branch-rule
