# The release pipeline will run only if all jobs in the test pipeline are successful

stages:
  - test
  - release

before_script:
  - npm install

release-test:
  image: node:18
  stage: test
  script:
    - env
    - echo $CI_COMMIT_REF_NAME != "main"
    - echo $CI_COMMIT_REF_NAME != "next"
    - echo $CI_COMMIT_REF_NAME != "next-major"
    - echo $CI_COMMIT_REF_NAME != "alpha" 
    - echo $CI_COMMIT_REF_NAME != "beta"
  rules:
    - if: $CI_COMMIT_REF_NAME != "main" || $CI_COMMIT_REF_NAME != "next" || $CI_COMMIT_REF_NAME != "next-major" || $CI_COMMIT_REF_NAME != "alpha" || $CI_COMMIT_REF_NAME != "beta"

publish:
  image: node:18
  stage: release
  script:
    - npm i
    - npm run release
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "next" || $CI_COMMIT_REF_NAME == "next-major" || $CI_COMMIT_REF_NAME == "alpha" || $CI_COMMIT_REF_NAME == "beta"